
//variable that calls the generateRandomColors function to create random colors for squares
var numSquares = 6;
var colors = generateRandomColors(numSquares);

var squares = document.querySelectorAll(".square");
var pickedColor = pickColor();
var colorDisplay = document.getElementById("colorDisplay");
var messageDisplay = document.querySelector("#message");
var h1 = document.querySelector("h1");
var resetButton = document.querySelector("#reset");
var easyBtn = document.querySelector("#easyBtn");
var hardBtn = document.querySelector("#hardBtn");

//easy button function
easyBtn.addEventListener("click", function(){
    //add remove classes to give the button its selected color to highlight it
    hardBtn.classList.remove("selected");
    easyBtn.classList.add("selected");
    numSquares = 3;
    //generate colors again but 3 values this time for the array
    colors = generateRandomColors(numSquares);
    //event to compare click to winning color
    pickedColor = pickColor();
    colorDisplay.textContent = pickedColor;

    for(var i = 0; i < squares.length; i++){
    if(colors[i]){
           squares[i].style.backgroundColor = colors[i];
        } else {
            squares[i].style.display = "none";
        }
    }
});

//hard button function
hardBtn.addEventListener("click", function(){
    hardBtn.classList.add("selected");
    easyBtn.classList.remove("selected");
    numSquares = 6;
    //generate 6 new colors for array
    colors = generateRandomColors(numSquares);
    //event to compare click to winning color
    pickedColor = pickColor();
    colorDisplay.textContent = pickedColor;

    for(var i = 0; i < squares.length; i++){
           squares[i].style.backgroundColor = colors[i];
            squares[i].style.display = "block";
    }
});


//Play new game button event
resetButton.addEventListener("click", function(){
    //generate all new colors
    colors = generateRandomColors(numSquares);
    //pick a new random color from array
    pickedColor = pickColor();
    //change colorDisplay to match picked color
    colorDisplay.textContent = pickedColor;
    this.textContent = "New colors";

    messageDisplay.textContent = "";
    //change colors of squares
    for(var i = 0; i < squares.length; i++){
        squares[i].style.backgroundColor = colors[i];
    }
    h1.style.backgroundColor = "steelbue";

});

//insert picked color from array into h1 header
colorDisplay.textContent = pickedColor;

//Function for checking if you have picked the correct color
//loop through squares to compare colors to pickedColor clickevent
for(var i = 0; i < squares.length; i++){
    //add initial colors to squares
    squares[i].style.backgroundColor = colors[i];
    //add click listeners to squares
    squares[i].addEventListener("click", function(){
        //grab color of clicked square
        var clickedColor = this.style.backgroundColor;
        //compare color to pickedColor
        if(clickedColor === pickedColor){
            messageDisplay.textContent = "Correct!";
            resetButton.textContent = "Play Again?";
            changeColors(clickedColor);
            h1.style.backgroundColor = clickedColor;
        } else {
            this.style.backgroundColor = "#232323";
            messageDisplay.textContent = "Try again";
        }
    });
}

function changeColors(color){
    //loop through all squares
    for(var i = 0; i < squares.length; i ++){
        //change each color to match given color
        squares[i].style.backgroundColor = color;
    }
    
}

//picks the winning color from the array the .length for colors gets how many are in the array
function pickColor(){
    var random = Math.floor(Math.random() * colors.length);
    return colors[random];
}


//pushes the numbers generated by randomColor function into the array
function generateRandomColors(num){
    //make array
    var arr = []
    //add num times
    for(var i = 0; i < num; i++){
        //get random color from function and push to array
        arr.push(randomColor())
    }
    //return that array
    return arr;
}

//function for generating a random rgb color and returns as rgb value 
function randomColor(){
    //pick a red from 0 to 255
    var r = Math.floor(Math.random() * 256);
    //pick a green from 0 to 255
    var g = Math.floor(Math.random() * 256);
    //pick a blue from 0 to 255
    var b = Math.floor(Math.random() * 256);
    return "rgb(" + r + ", " + g + ", " + b + ")"; 
}